# Dockerfile.dependencies

FROM python:3.12-slim

ENV http_proxy=deb.debian.org/debian
ENV https_proxy=deb.debian.org/debian

WORKDIR /app

COPY requirements-prod.txt /app

RUN apt-get update && apt-get install -y ffmpeg libsm6 libxext6
RUN pip install -r requirements-prod.txt
